### PR TITLE
Add oriented bounding box filter

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
This adds a new filter that creates a mesh with the vertices of the
optimal oriented bounding for an object. See
plugins/filter_orientedbbox/README.md for details.

### CODE REVIEW

**Comment by alemuntoni** [comment]
That's great, thanks @alfonsosanchezbeato!!

Before merging, I see that there are some build issues. I think that the plugin has been coded with some old meshlab version, therefore they should be not hard to solve. I'll look into them ASAP!

**Comment by alfonsosanchezbeato** [comment]
> That's great, thanks @alfonsosanchezbeato!!
> 
> Before merging, I see that there are some build issues. I think that the plugin has been coded with some old meshlab version, therefore they should be not hard to solve. I'll look into them ASAP!

Oh, right, there was a name change in a method. I've pushed a commit that should fix that.

**Comment by alemuntoni** [comment]
I modified and fixed minor things to make the plugin build also under windows, please check if these fixes are ok for you!!
Note that I had to replace `rand_r` to `rand`, since `rand_r` is not available in msvc. 
And since `rand` does not have an overload that takes a seed as parameter, I added the classic `srand(time(NULL))` to initialize the global seed. I'm not 100% sure that this solution is equivalent, though.

**Comment by alfonsosanchezbeato** [comment]
@alemuntoni thanks for your changes, sure, please go ahead and merge. I've seen a couple of strange things related to spaces in the diff, but no big deal.

**Comment by alemuntoni** [comment]
> @alemuntoni thanks for your changes, sure, please go ahead and merge. I've seen a couple of strange things related to spaces in the diff, but no big deal.

Yes, there were some consecutive lines that were indented one with spaces and one with tabs, and I adjusted coherently the indentation! No big deal!

Thanks again for your contribution! :)

**Pull request merged**
